name: RandomRoulette
version: '1.0-SNAPSHOT'
main: io.github.xian7720.randomroulette.RandomRoulettePlugin
api-version: '1.21'

commands:
  roulette:
    description: "rolling roulette"
    usage: "/roulette <int 1-10>"
    aliases: [r]


